### ISSUE TITLE
how to download the pretrained weights  to local

### ISSUE THREAD

**Issue by hischen** [alisafaya/Arabic-BERT#5]
Thans for your contribution! But how to download the pretrained weights to local ,would you pls offer me a url, thanks!

**Comment by alisafaya** [comment]
The model is hosted on [huggingface.co](huggingface.co)
You can access the model's files using this url [https://huggingface.co/asafaya/bert-base-arabic#list-files](https://huggingface.co/asafaya/bert-base-arabic#list-files)
