### ISSUE TITLE
Can't load weights

### ISSUE THREAD

**Issue by habibagamal** [alisafaya/Arabic-BERT#6]
Hello, 

This is the code I have so far
```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("asafaya/bert-base-arabic")
model = TFAutoModel.from_pretrained("asafaya/bert-base-arabic")
```

I get this error when I run it. 

> OSError: Can't load weights for 'asafaya/bert-base-arabic'. Make sure that:
> 
> - 'asafaya/bert-base-arabic' is a correct model identifier listed on 'https://huggingface.co/models'
> 
> - or 'asafaya/bert-base-arabic' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

I do not have the model locally on my machine, but it exists on  'https://huggingface.co/models'. Any idea what's causing this? 

Thanks.

**Comment by habibagamal** [comment]
I believe you may be missing the .h5 file needed when using tensorflow.

**Comment by habibagamal** [comment]
Update: I'm getting the same error when using pytorch as well.

**Comment by habibagamal** [comment]
Update 2: Loading the weights only works for asafaya/bert-base-arabic and asafaya/bert-large-arabic using pytorch and does not work for any of the 4 using tensorflow.

**Comment by alisafaya** [comment]
I've added tf_model.h5 files to the models
