### ISSUE TITLE
can't find the .cptk file

### ISSUE THREAD

**Issue by mukhtar-algezoli** [alisafaya/Arabic-BERT#7]
Thank you for your contribution to Arabic NLP,
I am trying to tune (continue pre-training) the pre-trained model on more task-specific data, and I can't download the model weights, specifically, I need the .cptk file.

**Comment by alisafaya** [comment]
Hi,

I haven't upload .ckpt file to huggingface portal. I will upload it as soon as possible. in the mean time you can convert pytorch model to tensorflow checkpoint using this script: [convert_bert_pytorch_checkpoint_to_original_tf.py](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bert_pytorch_checkpoint_to_original_tf.py) from transformers library.
