### ISSUE TITLE
Diacritic words

### ISSUE THREAD

**Issue by Alymostafa** [alisafaya/Arabic-BERT#9]
Did the datasets that you had used include words with their diacritics?

**Comment by alisafaya** [comment]
Yes it did, but not all the texts had diacritics.

**Comment by Alymostafa** [comment]
Can you give a rough percentage of diacritics words?

**Comment by alisafaya** [comment]
Unfortunately, I haven't extracted such statistics on the corpus

**Comment by Alymostafa** [comment]
can't you give me an arbitrary number?
